Add is_identical for zvals
davidcole1340/ext-php-rs pull request #217
Opened 2023-01-18 13:18 UTC by Christian-Rades

I was missing the ability to compare two zvals with PHP's `===` operator. 
To allow for it, I exposed the `zend_is_identical` function that the Zend engine maps to the `===` token.

2023-01-18 14:43 UTC, ptondereau requested changes

2023-01-18 14:43 UTC, ptondereau commented on docsrs_bindings.rs
> +pub const ZEND_MODULE_API_NO: u32 = 20210902;
you should use PHP8.2 to generate doc binding

2023-01-18 14:43 UTC, ptondereau commented on docsrs_bindings.rs
> +pub const ZEND_DEBUG: u32 = 0;
Please use a PHP version with debug mode

2023-01-18 14:43 UTC, ptondereau commented on src/types/zval.rs
> +
This addition is good! 👍🏻

2023-01-18 19:25 UTC, Christian-Rades commented on docsrs_bindings.rs
> +}
The diff looks way better now :sweat_smile:

2023-01-19 11:40 UTC, ptondereau approved these changes
LGTM thank you

2023-01-19 11:40 UTC, merged